sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_script:
  - npm prune
script:
  - ./next-update-travis.sh
  - npm run lint
  - npm run mocha
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
